"""Output contracts - system-level instructions that push the LLM to reply concisely."""
from __future__ import annotations

_WRAPPER_HEADER = """\
You are receiving a compressed context packet generated by a local ShapeShifter wrapper.
Treat the packet as the primary context. Do not ask for the original context unless the \
packet explicitly says more detail is required.
Answer according to the output contract below.
Avoid generic introductions. Do not restate the prompt.\
"""

_CONTRACTS: dict[str, str] = {
    "generation": """\
OUTPUT_CONTRACT:
- Return the COMPLETE, working file - never truncate.
- Output only the code block, no explanation before or after.
- Do not add "// ... rest of code ..." or any placeholder.
- Every feature requested must be present in the output.
- The code must run without errors in a browser (HTML) or interpreter.""",

    "code": """\
OUTPUT_CONTRACT:
- Provide only the changed lines or a unified diff.
- Explain in max 5 bullet points.
- Do not repeat the full file.
- No generic introduction.
- No disclaimer.""",

    "comparison": """\
OUTPUT_CONTRACT:
- Reply with a compact markdown table.
- Add max 3 observations after the table.
- No generic introduction.""",

    "email_text": """\
OUTPUT_CONTRACT:
- Return only the final requested text.
- No external comments or meta-explanation.""",

    "analysis": """\
OUTPUT_CONTRACT:
- Probable cause.
- Evidence (max 4 items).
- Next checks (max 3 items).
- Recommended solution.
- Max 800 tokens total.""",

    "generic": """\
OUTPUT_CONTRACT:
- Concise answer.
- No generic introduction.
- Max 8 bullets unless code is required.
- Show only relevant code or patch.""",
}


def build_system_prompt(mode: str, contract_type: str = "generic") -> str:
    contract = _CONTRACTS.get(contract_type, _CONTRACTS["generic"])
    return f"{_WRAPPER_HEADER}\n\nCONTEXT_MODE: {mode}\n\n{contract}"


def detect_contract_type(messages: list[dict]) -> str:
    """Heuristic: pick the contract type from the conversation."""
    all_text = " ".join(
        m.get("content", "") for m in messages if isinstance(m.get("content"), str)
    ).lower()
    if any(k in all_text for k in ("generate", "create", "build", "implement", "write", "make")):
        return "generation"
    if any(k in all_text for k in ("diff", "patch", "bug", "error", "fix", "debug", "exception", "traceback")):
        return "code"
    if any(k in all_text for k in ("compare", "comparison", "table", "difference")):
        return "comparison"
    if any(k in all_text for k in ("email", "letter", "message")):
        return "email_text"
    if any(k in all_text for k in ("analysis", "cause", "root cause", "performance")):
        return "analysis"
    return "generic"
